#
# Generated by "infrahubctl protocols"
#
# Regenerate with:
#   INFRAHUB_ADDRESS=http://localhost:8000 uv run infrahubctl protocols --out src/infrahub_solution_ai_dc/protocols.py
#
# One hand-edit is applied after each regeneration: for hierarchical generics
# (NetworkBuildingBlock, LocationPhysical) infrahubctl emits `parent` and `children` twice, and
# `ruff check` rejects the duplicate class fields. The two copies are identical, so the trailing
# pair is deleted — no change in meaning. Then run `uv run inv format`.
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPNamespace,
    BuiltinIPPrefix,
    BuiltinTag,
    CoreArtifact,
    CoreArtifactTarget,
    CoreGroup,
    CoreIPAddressPool,
    CoreIPPrefixPool,
    CoreNode,
    CoreNumberPool,
    CoreObjectComponentTemplate,
    CoreObjectTemplate,
    CoreProfile,
    IpamNamespace,
    LineageSource,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelationshipAttribute, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Boolean,
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPHostOptional,
        IPNetwork,
        IPNetworkOptional,
        String,
        StringOptional,
    )


class NetworkBGPPeer(CoreNode):
    hostname: String
    bgp_sessions: RelationshipManager[NetworkBGPSession]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkBuildingBlock(CoreNode):
    index: Integer
    name: String
    children: RelationshipManager[NetworkBuildingBlock]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[NetworkBuildingBlock]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class TemplateCoreArtifactTarget(CoreNode):
    template_name: String
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkEndpoint(CoreNode):
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class CoreIPPool(CoreNode):
    member_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class TemplateNetworkBGPPeer(CoreNode):
    template_name: String
    bgp_sessions: RelationshipManager[TemplateNetworkBGPSession]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class TemplateNetworkEndpoint(CoreNode):
    template_name: String
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class LocationPhysical(CoreNode):
    index: Integer
    name: String
    children: RelationshipManager[LocationPhysical]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[LocationPhysical]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class GeneratorTarget(CoreNode):
    checksum: StringOptional
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkBGPSession(CoreNode):
    address_family: Dropdown
    local_as: IntegerOptional
    name: String
    remote_as: IntegerOptional
    rr_client: Boolean
    device: RelationshipAttribute[NetworkBGPPeer]
    member_of_groups: RelationshipManager[CoreGroup]
    peer_device: RelationshipAttribute[NetworkBGPPeer]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkDevice(CoreArtifactTarget, NetworkBGPPeer):
    asn: IntegerOptional
    hostname: String
    index: IntegerOptional
    role: Dropdown
    route_reflector: Boolean
    artifacts: RelationshipManager[CoreArtifact]
    bgp_sessions: RelationshipManager[NetworkBGPSession]
    device_type: RelationshipAttribute[NetworkDeviceType]
    interfaces: RelationshipManager[NetworkInterface]
    loopback_ip: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreGroup]
    object_template: RelationshipAttribute[TemplateNetworkDevice]
    pod: RelationshipAttribute[NetworkPod]
    profiles: RelationshipManager[CoreProfile]
    rack: RelationshipAttribute[LocationRack]
    segments: RelationshipManager[NetworkSegment]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vtep_ip: RelationshipAttribute[IpamIPAddress]


class NetworkDeviceType(CoreNode):
    name: String
    devices: RelationshipManager[NetworkDevice]
    manufacturer: RelationshipAttribute[OrganizationManufacturer]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkFabric(CoreArtifactTarget, NetworkBuildingBlock):
    amount_of_super_spines: Integer
    anycast_gateway_mac: StringOptional
    fabric_interface_sorting_method: Dropdown
    index: Integer
    name: String
    overlay_asn: IntegerOptional
    routing_design: Dropdown
    spine_interface_sorting_method: Dropdown
    artifacts: RelationshipManager[CoreArtifact]
    children: RelationshipManager[NetworkPod]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[NetworkBuildingBlock]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    super_spine_switch_template: RelationshipAttribute[CoreObjectTemplate]


class LocationHall(LocationPhysical):
    index: Integer
    name: String
    children: RelationshipManager[LocationRack]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[LocationPhysical]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    ip_prefix: RelationshipAttribute[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class IpamIPPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: Boolean
    is_top_level: BooleanOptional
    member_type: Dropdown
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: Dropdown
    utilization: IntegerOptional
    children: RelationshipManager[BuiltinIPPrefix]
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[BuiltinIPPrefix]
    profiles: RelationshipManager[CoreProfile]
    resource_pool: RelationshipManager[CoreIPPool]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkInterface(NetworkEndpoint):
    description: StringOptional
    index: StringOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    device: RelationshipAttribute[NetworkDevice]
    ip_address: RelationshipAttribute[IpamIPAddress]
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ServerInterface(NetworkEndpoint):
    description: StringOptional
    mtu: IntegerOptional
    name: String
    role: Dropdown
    status: Dropdown
    ip_address: RelationshipAttribute[IpamIPAddress]
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    server: RelationshipAttribute[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkKubernetesCluster(CoreArtifactTarget):
    description: StringOptional
    name: String
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    members: RelationshipManager[NetworkServerService]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkLink(CoreNode):
    medium: Dropdown
    name: String
    endpoints: RelationshipManager[NetworkEndpoint]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class OrganizationManufacturer(CoreNode):
    name: String
    device_types: RelationshipManager[NetworkDeviceType]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkPod(NetworkBuildingBlock, GeneratorTarget):
    amount_of_spines: Integer
    checksum: StringOptional
    index: Integer
    leaf_interface_sorting_method: Dropdown
    name: String
    role: Dropdown
    spine_interface_sorting_method: Dropdown
    children: RelationshipManager[NetworkBuildingBlock]
    devices: RelationshipManager[NetworkDevice]
    loopback_pool: RelationshipAttribute[CoreIPAddressPool]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[NetworkFabric]
    prefix_pool: RelationshipAttribute[CoreIPPrefixPool]
    profiles: RelationshipManager[CoreProfile]
    racks: RelationshipManager[LocationRack]
    server_prefix_pool: RelationshipAttribute[CoreIPPrefixPool]
    spine_switch_template: RelationshipAttribute[CoreObjectTemplate]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vtep_pool: RelationshipAttribute[CoreIPAddressPool]


class LocationRack(LocationPhysical, GeneratorTarget):
    amount_of_leafs: Integer
    checksum: StringOptional
    index: Integer
    name: String
    rack_type: Dropdown
    children: RelationshipManager[LocationPhysical]
    devices: RelationshipManager[NetworkDevice]
    leaf_switch_template: RelationshipAttribute[CoreObjectTemplate]
    member_of_groups: RelationshipManager[CoreGroup]
    parent: RelationshipAttribute[LocationHall]
    pod: RelationshipAttribute[NetworkPod]
    profiles: RelationshipManager[CoreProfile]
    servers: RelationshipManager[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkSegment(CoreNode):
    l2vni: IntegerOptional
    name: String
    route_target: StringOptional
    routed: Boolean
    vlan_id: IntegerOptional
    gateway: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    racks: RelationshipManager[LocationRack]
    subnet: RelationshipAttribute[IpamIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vrf: RelationshipAttribute[NetworkVrf]


class NetworkServer(NetworkBGPPeer):
    asn: IntegerOptional
    hostname: String
    layer: DropdownOptional
    node_selector: StringOptional
    bgp_sessions: RelationshipManager[NetworkBGPSession]
    interfaces: RelationshipManager[ServerInterface]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    rack: RelationshipAttribute[LocationRack]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class NetworkServerService(GeneratorTarget):
    checksum: StringOptional
    layer: Dropdown
    name: String
    kubernetes_cluster: RelationshipAttribute[NetworkKubernetesCluster]
    leaf_interface: RelationshipAttribute[NetworkInterface]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    rack: RelationshipAttribute[LocationRack]
    segment: RelationshipAttribute[NetworkSegment]
    server: RelationshipAttribute[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vrf: RelationshipAttribute[NetworkVrf]


class NetworkTenant(GeneratorTarget):
    checksum: StringOptional
    name: String
    fabric: RelationshipAttribute[NetworkFabric]
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vrfs: RelationshipManager[NetworkVrf]


class NetworkVrf(CoreNode):
    export_rt: StringOptional
    import_rt: StringOptional
    l3_vlan_id: IntegerOptional
    l3vni: IntegerOptional
    name: String
    route_target: StringOptional
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    profiles: RelationshipManager[CoreProfile]
    segments: RelationshipManager[NetworkSegment]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    tenant: RelationshipAttribute[NetworkTenant]


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    address: IPHostOptional
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinIPAddress]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    prefix: IPNetworkOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[BuiltinTag]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileGeneratorTarget(LineageSource, CoreProfile, CoreNode):
    checksum: StringOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[GeneratorTarget]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    address: IPHostOptional
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[IpamIPAddress]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileIpamIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: Integer
    role: DropdownOptional
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[IpamIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    ip_addresses: RelationshipManager[BuiltinIPAddress]
    ip_prefixes: RelationshipManager[BuiltinIPPrefix]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[IpamNamespace]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileLocationHall(LineageSource, CoreProfile, CoreNode):
    index: IntegerOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[LocationHall]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileLocationPhysical(LineageSource, CoreProfile, CoreNode):
    index: IntegerOptional
    name: StringOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[LocationPhysical]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileLocationRack(LineageSource, CoreProfile, CoreNode):
    amount_of_leafs: IntegerOptional
    checksum: StringOptional
    profile_name: String
    profile_priority: Integer
    rack_type: DropdownOptional
    devices: RelationshipManager[NetworkDevice]
    leaf_switch_template: RelationshipAttribute[CoreObjectTemplate]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[LocationRack]
    servers: RelationshipManager[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkBGPPeer(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkBGPPeer]
    related_templates: RelationshipManager[TemplateNetworkBGPPeer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkBGPSession(LineageSource, CoreProfile, CoreNode):
    address_family: DropdownOptional
    local_as: IntegerOptional
    profile_name: String
    profile_priority: Integer
    remote_as: IntegerOptional
    rr_client: BooleanOptional
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkBGPSession]
    related_templates: RelationshipManager[TemplateNetworkBGPSession]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkBuildingBlock(LineageSource, CoreProfile, CoreNode):
    index: IntegerOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkBuildingBlock]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkDevice(LineageSource, CoreProfile, CoreNode):
    asn: IntegerOptional
    index: IntegerOptional
    profile_name: String
    profile_priority: Integer
    role: DropdownOptional
    route_reflector: BooleanOptional
    artifacts: RelationshipManager[CoreArtifact]
    device_type: RelationshipAttribute[NetworkDeviceType]
    loopback_ip: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreGroup]
    pod: RelationshipAttribute[NetworkPod]
    rack: RelationshipAttribute[LocationRack]
    related_nodes: RelationshipManager[NetworkDevice]
    related_templates: RelationshipManager[TemplateNetworkDevice]
    segments: RelationshipManager[NetworkSegment]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vtep_ip: RelationshipAttribute[IpamIPAddress]


class ProfileNetworkDeviceType(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: Integer
    devices: RelationshipManager[NetworkDevice]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkDeviceType]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkEndpoint(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: Integer
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkEndpoint]
    related_templates: RelationshipManager[TemplateNetworkEndpoint]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkFabric(LineageSource, CoreProfile, CoreNode):
    amount_of_super_spines: IntegerOptional
    anycast_gateway_mac: StringOptional
    fabric_interface_sorting_method: DropdownOptional
    index: IntegerOptional
    overlay_asn: IntegerOptional
    profile_name: String
    profile_priority: Integer
    routing_design: DropdownOptional
    spine_interface_sorting_method: DropdownOptional
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkFabric]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    super_spine_switch_template: RelationshipAttribute[CoreObjectTemplate]


class ProfileNetworkInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: Integer
    role: DropdownOptional
    status: DropdownOptional
    ip_address: RelationshipAttribute[IpamIPAddress]
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkInterface]
    related_templates: RelationshipManager[TemplateNetworkInterface]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkKubernetesCluster(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: Integer
    artifacts: RelationshipManager[CoreArtifact]
    member_of_groups: RelationshipManager[CoreGroup]
    members: RelationshipManager[NetworkServerService]
    related_nodes: RelationshipManager[NetworkKubernetesCluster]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkLink(LineageSource, CoreProfile, CoreNode):
    medium: DropdownOptional
    profile_name: String
    profile_priority: Integer
    endpoints: RelationshipManager[NetworkEndpoint]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkLink]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkPod(LineageSource, CoreProfile, CoreNode):
    amount_of_spines: IntegerOptional
    checksum: StringOptional
    index: IntegerOptional
    leaf_interface_sorting_method: DropdownOptional
    profile_name: String
    profile_priority: Integer
    role: DropdownOptional
    spine_interface_sorting_method: DropdownOptional
    devices: RelationshipManager[NetworkDevice]
    loopback_pool: RelationshipAttribute[CoreIPAddressPool]
    member_of_groups: RelationshipManager[CoreGroup]
    prefix_pool: RelationshipAttribute[CoreIPPrefixPool]
    racks: RelationshipManager[LocationRack]
    related_nodes: RelationshipManager[NetworkPod]
    server_prefix_pool: RelationshipAttribute[CoreIPPrefixPool]
    spine_switch_template: RelationshipAttribute[CoreObjectTemplate]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vtep_pool: RelationshipAttribute[CoreIPAddressPool]


class ProfileNetworkSegment(LineageSource, CoreProfile, CoreNode):
    l2vni: IntegerOptional
    profile_name: String
    profile_priority: Integer
    route_target: StringOptional
    routed: BooleanOptional
    vlan_id: IntegerOptional
    gateway: RelationshipAttribute[IpamIPAddress]
    member_of_groups: RelationshipManager[CoreGroup]
    racks: RelationshipManager[LocationRack]
    related_nodes: RelationshipManager[NetworkSegment]
    subnet: RelationshipAttribute[IpamIPPrefix]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkServer(LineageSource, CoreProfile, CoreNode):
    asn: IntegerOptional
    layer: DropdownOptional
    profile_name: String
    profile_priority: Integer
    member_of_groups: RelationshipManager[CoreGroup]
    rack: RelationshipAttribute[LocationRack]
    related_nodes: RelationshipManager[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkServerService(LineageSource, CoreProfile, CoreNode):
    checksum: StringOptional
    layer: DropdownOptional
    profile_name: String
    profile_priority: Integer
    kubernetes_cluster: RelationshipAttribute[NetworkKubernetesCluster]
    leaf_interface: RelationshipAttribute[NetworkInterface]
    member_of_groups: RelationshipManager[CoreGroup]
    rack: RelationshipAttribute[LocationRack]
    related_nodes: RelationshipManager[NetworkServerService]
    segment: RelationshipAttribute[NetworkSegment]
    server: RelationshipAttribute[NetworkServer]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    vrf: RelationshipAttribute[NetworkVrf]


class ProfileNetworkTenant(LineageSource, CoreProfile, CoreNode):
    checksum: StringOptional
    profile_name: String
    profile_priority: Integer
    fabric: RelationshipAttribute[NetworkFabric]
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkTenant]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileNetworkVrf(LineageSource, CoreProfile, CoreNode):
    export_rt: StringOptional
    import_rt: StringOptional
    l3_vlan_id: IntegerOptional
    l3vni: IntegerOptional
    profile_name: String
    profile_priority: Integer
    route_target: StringOptional
    ip_namespace: RelationshipAttribute[BuiltinIPNamespace]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[NetworkVrf]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileOrganizationManufacturer(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: Integer
    device_types: RelationshipManager[NetworkDeviceType]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[OrganizationManufacturer]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class ProfileServerInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: Integer
    role: DropdownOptional
    status: DropdownOptional
    ip_address: RelationshipAttribute[IpamIPAddress]
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    related_nodes: RelationshipManager[ServerInterface]
    subscriber_of_groups: RelationshipManager[CoreGroup]


class TemplateNetworkBGPSession(LineageSource, CoreObjectComponentTemplate, CoreNode):
    address_family: Dropdown
    local_as: IntegerOptional
    remote_as: IntegerOptional
    rr_client: Boolean
    template_name: String
    device: RelationshipAttribute[TemplateNetworkBGPPeer]
    local_as_from_resource_pool: RelationshipAttribute[CoreNumberPool]
    member_of_groups: RelationshipManager[CoreGroup]
    member_of_groups_for_instances: RelationshipManager[CoreGroup]
    peer_device: RelationshipAttribute[NetworkBGPPeer]
    profiles: RelationshipManager[CoreProfile]
    related_nodes: RelationshipManager[NetworkBGPSession]
    remote_as_from_resource_pool: RelationshipAttribute[CoreNumberPool]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups_for_instances: RelationshipManager[CoreGroup]


class TemplateNetworkDevice(
    LineageSource, TemplateCoreArtifactTarget, TemplateNetworkBGPPeer, CoreObjectTemplate, CoreNode
):
    asn: IntegerOptional
    index: IntegerOptional
    role: DropdownOptional
    route_reflector: Boolean
    template_name: String
    artifacts: RelationshipManager[CoreArtifact]
    asn_from_resource_pool: RelationshipAttribute[CoreNumberPool]
    bgp_sessions: RelationshipManager[TemplateNetworkBGPSession]
    device_type: RelationshipAttribute[NetworkDeviceType]
    index_from_resource_pool: RelationshipAttribute[CoreNumberPool]
    interfaces: RelationshipManager[TemplateNetworkInterface]
    loopback_ip: RelationshipAttribute[IpamIPAddress]
    loopback_ip_from_resource_pool: RelationshipAttribute[CoreIPAddressPool]
    member_of_groups: RelationshipManager[CoreGroup]
    member_of_groups_for_instances: RelationshipManager[CoreGroup]
    pod: RelationshipAttribute[NetworkPod]
    profiles: RelationshipManager[CoreProfile]
    rack: RelationshipAttribute[LocationRack]
    related_nodes: RelationshipManager[NetworkDevice]
    segments: RelationshipManager[NetworkSegment]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups_for_instances: RelationshipManager[CoreGroup]
    vtep_ip: RelationshipAttribute[IpamIPAddress]
    vtep_ip_from_resource_pool: RelationshipAttribute[CoreIPAddressPool]


class TemplateNetworkInterface(LineageSource, CoreObjectComponentTemplate, TemplateNetworkEndpoint, CoreNode):
    description: StringOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    template_name: String
    device: RelationshipAttribute[TemplateNetworkDevice]
    ip_address: RelationshipAttribute[IpamIPAddress]
    ip_address_from_resource_pool: RelationshipAttribute[CoreIPAddressPool]
    link: RelationshipAttribute[NetworkLink]
    member_of_groups: RelationshipManager[CoreGroup]
    member_of_groups_for_instances: RelationshipManager[CoreGroup]
    mtu_from_resource_pool: RelationshipAttribute[CoreNumberPool]
    profiles: RelationshipManager[CoreProfile]
    related_nodes: RelationshipManager[NetworkInterface]
    subscriber_of_groups: RelationshipManager[CoreGroup]
    subscriber_of_groups_for_instances: RelationshipManager[CoreGroup]
