#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreNode,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        Dropdown,
        DropdownOptional,
        Integer,
        String,
        StringOptional,
    )


class NetworkBuilder(CoreNode):
    name: String
    parent_checksum: StringOptional
    building_block: RelatedNode


class NetworkBuildingBlock(CoreNode):
    checksum: StringOptional
    index: Integer
    name: String


class NetworkEndpoint(CoreNode):
    link: RelatedNode


class LocationPhysical(CoreNode):
    index: Integer
    name: String


class NetworkDevice(CoreNode):
    hostname: String
    role: Dropdown
    interfaces: RelationshipManager
    loopback_ip: RelatedNode
    pod: RelatedNode
    rack: RelatedNode


class NetworkFabric(NetworkBuildingBlock):
    pass


class LocationHall(LocationPhysical):
    pass


class IpamIPAddress(BuiltinIPAddress):
    pass


class IpamIPPrefix(BuiltinIPPrefix):
    role: Dropdown


class NetworkInterface(NetworkEndpoint):
    index: StringOptional
    name: String
    role: DropdownOptional
    device: RelatedNode
    ip_address: RelatedNode


class NetworkLink(CoreNode):
    medium: Dropdown
    name: String
    endpoints: RelationshipManager


class NetworkPod(NetworkBuildingBlock):
    role: DropdownOptional
    devices: RelationshipManager
    racks: RelationshipManager


class NetworkPodBuilder(NetworkBuilder):
    pass


class LocationRack(LocationPhysical):
    devices: RelationshipManager
    pod: RelatedNode
