---
# schemas:
#   - schemas

queries:
  - name: generate_fabric
    file_path: "./generators/generate_fabric.gql"

  - name: generate_pod
    file_path: "./generators/generate_pod.gql"

  - name: generate_rack
    file_path: "./generators/generate_rack.gql"


# generator_definitions:
#   - name: generate-fabric
#     file_path: "./generators/generate_fabric.py"
#     query: generate_fabric
#     targets: fabrics
#     class_name: FabricGenerator
#     convert_query_response: false

#   - name: generate-pod
#     file_path: "./generators/generate_pod.py"
#     query: generate_pod
#     targets: pods
#     class_name: PodGenerator
#     convert_query_response: false

#   - name: generate-rack
#     file_path: "./generators/generate_rack.py"
#     query: generate_rack
#     targets: racks
#     class_name: RackGenerator
#     convert_query_response: false
