---
schemas:
  - schemas

menus:
  - menus/menu.yml

queries:
  - name: generate_fabric
    file_path: "./generators/generate_fabric.gql"

  - name: generate_pod
    file_path: "./generators/generate_pod.gql"

  - name: generate_rack
    file_path: "./generators/generate_rack.gql"


generator_definitions:
  - name: generate-fabric
    file_path: "./generators/generate_fabric.py"
    query: generate_fabric
    targets: fabrics
    parameters:
      fabric_name: name__value
    class_name: FabricGenerator
    convert_query_response: false
    # execute_in_proposed_change: false
    # execute_after_merge: false

  - name: generate-pod
    file_path: "./generators/generate_pod.py"
    query: generate_pod
    targets: pods
    parameters:
      pod_name: name__value
    class_name: PodGenerator
    convert_query_response: false
    # execute_in_proposed_change: false
    # execute_after_merge: false

  - name: generate-rack
    file_path: "./generators/generate_rack.py"
    query: generate_rack
    targets: racks
    parameters:
      rack_name: name__value
    class_name: RackGenerator
    convert_query_response: false
    # execute_in_proposed_change: false
    # execute_after_merge: false
