---
x-infrahub-custom-build: &infrahub_custom_build
  image: opsmill/infrahub-solution-ai-dc:${INFRAHUB_BASE_VERSION:-1.6.0}
  environment:
    INFRAHUB_GIT_USER_NAME: "infrahub"
    INFRAHUB_GIT_EMAIL: "no-reply@opsmill.com"
    INFRAHUB_GIT_USE_EXPLICIT_MERGE_COMMIT: true
    INFRAHUB_TIMEOUT: 180
  build:
    context: .
    dockerfile: Dockerfile
    args:
      INFRAHUB_BASE_VERSION: "${INFRAHUB_BASE_VERSION:-1.6.0}"

services:
  infrahub-server:
    <<: *infrahub_custom_build
  database:
    ports:
      - 7474:7474
      - 7687:7687

  task-manager:
    <<: *infrahub_custom_build
    ports:
      - 4200:4200

  task-worker:
    <<: *infrahub_custom_build
    volumes:
      - ./:/upstream
      - ./src:/opt/local/src
