---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: NetworkFabric
  data:
    - name: "Fabric-A"
      index: 1
      member_of_groups: ["fabrics"]
      children:
        kind: NetworkPod
        data:
          - name: "Pod-A1"
            index: 1
            role: "fabric"
            member_of_groups: ["pods"]
          - name: "Pod-A2"
            index: 2
            member_of_groups: ["pods"]
          - name: "Pod-A3"
            index: 3
            member_of_groups: ["pods"]
    - name: "Fabric-B"
      index: 2
      member_of_groups: ["fabrics"]
      children:
        kind: NetworkPod
        data:
          - name: "Pod-B1"
            index: 1
            role: "fabric"
            member_of_groups: ["pods"]
          - name: "Pod-B2"
            index: 2
            member_of_groups: ["pods"]
          - name: "Pod-B3"
            index: 3
            member_of_groups: ["pods"]
