---
apiVersion: infrahub.app/v1
kind: Object
spec:
  kind: TemplateNetworkDevice
  data:
    - template_name: "Generic Switch"
      interfaces:
        kind: TemplateNetworkInterface
        data:
          - template_name: "GenericSwitchEthernet1"
            name: "Ethernet1"
          - template_name: "GenericSwitchEthernet2"
            name: "Ethernet2"
          - template_name: "GenericSwitchEthernet3"
            name: "Ethernet3"
          - template_name: "GenericSwitchEthernet4"
            name: "Ethernet4"
          - template_name: "GenericSwitchEthernet5"
            name: "Ethernet5"
          - template_name: "GenericSwitchEthernet6"
            name: "Ethernet6"
          - template_name: "GenericSwitchEthernet7"
            name: "Ethernet7"
          - template_name: "GenericSwitchEthernet8"
            name: "Ethernet8"
          - template_name: "GenericSwitchEthernet9"
            name: "Ethernet9"
          - template_name: "GenericSwitchEthernet10"
            name: "Ethernet10"
          - template_name: "GenericSwitchEthernet11"
            name: "Ethernet11"
          - template_name: "GenericSwitchEthernet12"
            name: "Ethernet12"
          - template_name: "GenericSwitchEthernet13"
            name: "Ethernet13"
          - template_name: "GenericSwitchEthernet14"
            name: "Ethernet14"
          - template_name: "GenericSwitchEthernet15"
            name: "Ethernet15"
          - template_name: "GenericSwitchEthernet16"
            name: "Ethernet16"
          - template_name: "GenericSwitchEthernet17"
            name: "Ethernet17"
          - template_name: "GenericSwitchEthernet18"
            name: "Ethernet18"
          - template_name: "GenericSwitchEthernet19"
            name: "Ethernet19"
          - template_name: "GenericSwitchEthernet20"
            name: "Ethernet20"
          - template_name: "GenericSwitchEthernet21"
            name: "Ethernet21"
          - template_name: "GenericSwitchEthernet22"
            name: "Ethernet22"
          - template_name: "GenericSwitchEthernet23"
            name: "Ethernet23"
          - template_name: "GenericSwitchEthernet24"
            name: "Ethernet24"
          - template_name: "GenericSwitchEthernet25"
            name: "Ethernet25"
          - template_name: "GenericSwitchEthernet26"
            name: "Ethernet26"
          - template_name: "GenericSwitchEthernet27"
            name: "Ethernet27"
          - template_name: "GenericSwitchEthernet28"
            name: "Ethernet28"
          - template_name: "GenericSwitchEthernet29"
            name: "Ethernet29"
          - template_name: "GenericSwitchEthernet30"
            name: "Ethernet30"
          - template_name: "GenericSwitchEthernet31"
            name: "Ethernet31"
          - template_name: "GenericSwitchEthernet32"
            name: "Ethernet32"