query($rack_name: String!) {
  LocationRackBuilder(name__value: $rack_name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
        target {
          node {
            ... on LocationRack {
              id
              name {
                value
              }
              index {
                value
              }
              parent {
                node {
                  id
                  name {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}