query ($pod_name: String!) {
  NetworkPodBuilder(name__value: $pod_name) {
    edges {
      node {
        id
        name {
          value
        }
        parent_checksum {
          value
        }
        building_block {
          node {
            ... on NetworkPod {
              name {
                value
              }
              id
              index {
                value
              }
              parent {
                node {
                  id
                  name {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
