query($fabric_name: String!) {
    NetworkFabric(name__value: $fabric_name) {
        edges {
            node {
                id
                name {
                    value
                }
            }
        }
    }
}
