query ($pod_name: String!) {
  NetworkPod(name__value: $pod_name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
        index {
          value
        }
        role {
          value
        }
        parent {
          node {
            id
            name {
              value
            }
            amount_of_super_spines {
              value
            }
          }
        }
      }
    }
  }
}
