query($rack_name: String!) {
  LocationRackBuilder(name__value: $rack_name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
        target {
          node {
            ... on LocationRack {
              id
              name {
                value
              }
              index {
                value
              }
              rack_type {
                value
              }
              parent {
                node {
                  id
                  name {
                    value
                  }
                }
              }
              pod {
                node {
                  id
                  name {
                    value
                  }
                  index {
                    value
                  }
                  prefix_pool {
                    node {
                      id
                    }
                  }
                  loopback_pool {
                    node {
                      id
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}