query($rack_name: String!) {
  LocationRack(name__value: $rack_name) {
    edges {
      node {
        id
        name {
          value
        }
        checksum {
          value
        }
	index {
	  value
	}
	rack_type {
	  value
	}
	parent {
	  node {
	    id
	    name {
	      value
	    }
	  }
	}
	pod {
	  node {
	    id
	    name {
	      value
	    }
	    index {
	      value
	    }
	    prefix_pool {
	      node {
		id
	      }
	    }
	    loopback_pool {
	      node {
		id
	      }
	    }
	  }
	}
      }
    }
  }
}
