query FabricGeneratorQuery($fabric_name: String!) {
  NetworkFabric(name__value: $fabric_name) {
    edges {
      node {
        id
        name {
          value
        }
        amount_of_super_spines {
          value
        }
        super_spine_switch_template {
          node {
            __typename
            id
          }
        }
      }
    }
  }
}
