query FabricCablingPlanQuery($name: String!) {
  NetworkFabric(name__value: $name) {
    edges {
      node {
        __typename
        children {
          edges {
            node {
              __typename
              id
              ... on NetworkPod {
                devices {
                  edges {
                    node {
                      __typename
                      id
                      rack {
                        node {
                          __typename
                          id
                        }
                      }
                      interfaces {
                        edges {
                          node {
                            __typename
                            id
                            link {
                              node {
                                __typename
                                id
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
