query ComputedInterfaceDescriptionQuery($id: ID!) {
  NetworkInterface(ids: [$id]) {
    edges {
      node {
        __typename
        id
        link {
          node {
            __typename
            id
            endpoints {
              edges {
                node {
                  __typename
                  id
                  ... on NetworkInterface {
                    name {
                      value
                    }
                    device {
                      node {
                        __typename
                        hostname {
                          value
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
