query ComputedInterfaceDescription($id: ID!) {
  NetworkInterface(ids: [$id]) {
    edges {
      node {
	id
	link {
	  node {
	    id
	    endpoints {
	      edges {
		node {
		  id
		  ... on NetworkInterface {
		    name {
		      value
		    }
		    device {
		      node {
			hostname {
			  value
			}
		      }
		    }
		  }
		}
	      }
	    }
	  }
	}
      }
    }
  }
}
