query StartupConfigQuery($name: String!){
  NetworkDevice(hostname__value: $name) {
    edges {
      node {
        __typename
        hostname {
          value
        }
        role {
          value
        }
        asn {
          value
        }
        loopback_ip {
          node {
            __typename
            address {
              ip
            }
          }
        }
        vtep_ip {
          node {
            __typename
            address {
              value
            }
          }
        }
        pod {
          node {
            __typename
            parent {
              node {
                __typename
                ... on NetworkFabric {
                  overlay_asn {
                    value
                  }
                  anycast_gateway_mac {
                    value
                  }
                }
              }
            }
          }
        }
        interfaces {
          edges {
            node {
              __typename
              name {
                value
              }
              description {
                value
              }
              role {
                value
              }
              status {
                value
              }
              ip_address {
                node {
                  __typename
                  address {
                    value
                  }
                }
              }
            }
          }
        }
        bgp_sessions {
          edges {
            node {
              __typename
              name {
                value
              }
              remote_as {
                value
              }
              local_as {
                value
              }
              address_family {
                value
              }
              rr_client {
                value
              }
              peer_device {
                node {
                  __typename
                  hostname {
                    value
                  }
                  loopback_ip {
                    node {
                      __typename
                      address {
                        ip
                      }
                    }
                  }
                  ... on NetworkServer {
                    interfaces {
                      edges {
                        node {
                          __typename
                          ip_address {
                            node {
                              __typename
                              address {
                                value
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        segments {
          edges {
            node {
              __typename
              name {
                value
              }
              vlan_id {
                value
              }
              l2vni {
                value
              }
              route_target {
                value
              }
              routed {
                value
              }
              subnet {
                node {
                  __typename
                  prefix {
                    value
                  }
                }
              }
              gateway {
                node {
                  __typename
                  address {
                    value
                  }
                }
              }
              vrf {
                node {
                  __typename
                  name {
                    value
                  }
                  l3vni {
                    value
                  }
                  l3_vlan_id {
                    value
                  }
                  route_target {
                    value
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
